site_name: robotframework-testdoc
repo_url: https://github.com/MarvKler/robotframework-testdoc
edit_uri: https://github.com/MarvKler/robotframework-testdoc/blob/main/docs/mkdocs/docs


theme:
  name: material
  logo: stylesheets/logo-white.png
  favicon: stylesheets/logo.png
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.indexes
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  palette:
    scheme: slate
    primary: custom

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - CLI:
    - cli/cli.md
  - API:
    - api/api.md
  - Usage: 
    - usage/index.md
    - Getting Started: usage/gettingstarted.md
    - Jinja2: usage/jinja2.md
    - Mkdocs: usage/mkdocs.md
  - Advanced Usage:
    - advanced_usage/index.md